export type Clef = 'treble' | 'bass' | 'alto' | 'tenor';

export type NoteDuration = 
  | 'whole' 
  | 'half' 
  | 'quarter' 
  | 'eighth' 
  | 'sixteenth' 
  | 'thirty-second'
  | 'dotted-whole'
  | 'dotted-half'
  | 'dotted-quarter'
  | 'dotted-eighth'
  | 'dotted-sixteenth'
  | 'dotted-thirty-second'
  | 'triplet-half'
  | 'triplet-quarter'
  | 'triplet-eighth'
  | 'triplet-sixteenth'
  | 'triplet-thirty-second'
  | 'quintuplet-half'
  | 'quintuplet-quarter'
  | 'quintuplet-eighth'
  | 'quintuplet-sixteenth'
  | 'quintuplet-thirty-second'
  | 'sextuplet-half'
  | 'sextuplet-quarter'
  | 'sextuplet-eighth'
  | 'sextuplet-sixteenth'
  | 'sextuplet-thirty-second'
  | 'septuplet-half'
  | 'septuplet-quarter'
  | 'septuplet-eighth'
  | 'septuplet-sixteenth'
  | 'septuplet-thirty-second';

export type Accidental = 'sharp' | 'flat' | 'natural' | 'double-sharp' | 'double-flat' | null;

export type Pitch = string; // e.g., "C4", "E#5", "Bb3"

/** Controls which side a slur/tie arc curves toward. */
export type SlurDirection = 'auto' | 'above' | 'below';
export type HairpinDirection = 'crescendo' | 'decrescendo';

export interface Note {
  pitch: Pitch;
  duration: NoteDuration;
  accidental?: Accidental;
  /** Optional lyric syllable/text rendered beneath the note head. */
  lyric?: string;
  tie?: boolean;
  slur?: boolean;
  /** Override the automatic arc direction for the SLUR arc this note belongs to. */
  slurDirection?: SlurDirection;
  /** Override the automatic arc direction for the TIE arc on this specific note.
   *  Intentionally separate from slurDirection so a tie inside a slur phrase
   *  can have its own independent direction. */
  tieDirection?: SlurDirection;
  articulation?: string;
  dynamic?: string;
  /** Start a hairpin at this note (< or >). */
  hairpinStart?: HairpinDirection;
  /** End the currently active hairpin at this note. */
  hairpinEnd?: boolean;
  /** Gregorian chant note shape used when notationSystem is gregorian-chant. */
  chantSymbol?: GregorianChantSymbol;
  /** Optional chant ornament mark for the note. */
  chantOrnament?: GregorianChantOrnament;
}

export interface Rest {
  duration: NoteDuration;
  /**
   * Timing-only rest placeholder used by import pipelines (e.g. scanned polyphony).
   * Hidden rests keep beat alignment without cluttering notation output.
   */
  hidden?: boolean;
}

export type MusicElement = Note | Rest;

export interface Voice {
  notes: MusicElement[];
}

export interface ChordSymbol {
  /** Chord symbol text (e.g., "Cm7", "F/A", "G7sus") */
  symbol: string;
  /** Position in beats from the start of the measure (0 = start of measure) */
  beat: number;
}

export interface Measure {
  number: number;
  voices: Voice[];
  /**
   * Mid-composition changes applied AT THE START of this measure.
   * Each field is optional; if absent the previous (or global) value stays in effect.
   */
  timeSignature?: string; // e.g. "3/4" – changes time sig from this measure onward
  keySignature?: string;  // e.g. "G" – changes key sig from this measure onward
  tempo?: number;         // BPM – changes tempo from this measure onward
  clef?: Clef;            // clef change for this staff from this measure onward
  /** Chord symbols displayed above the staff */
  chords?: ChordSymbol[];
  /** Gregorian chant division marker drawn at the end of this measure. */
  chantDivision?: GregorianChantDivision;
}

export interface Staff {
  clef: Clef;
  instrument: string;
  measures: Measure[];
  name?: string; // Optional custom name for the staff
  /** True when this staff was generated by AI arrangement tools. */
  aiGenerated?: boolean;
  /** Hide in score UI and PDF/print output; playback still includes this staff. */
  hidden?: boolean;
}

export type PrivacyLevel = 'private' | 'shared' | 'public';
export type NotationSystem = 'standard' | 'gregorian-chant';
export type GregorianChantSymbol =
  | 'punctum'
  | 'virga'
  | 'podatus'
  | 'clivis'
  | 'torculus'
  | 'porrectus'
  | 'quilisma'
  | 'liquescent';
export type GregorianChantOrnament = 'none' | 'episema' | 'mora';
export type GregorianChantDivision = 'none' | 'minima' | 'minor' | 'major' | 'finalis';
export type GregorianChantSpacingDensity = 'tight' | 'normal' | 'spacious';
export type GregorianChantInterpretation = 'subtle' | 'medium' | 'expressive';

export interface LinkedPartSource {
  /** Source full-score composition id this part is derived from. */
  compositionId: string;
  /** Staff index in the source score used to build this part. */
  staffIndex: number;
  /** Optional voice index (0-3) when this linked part captures a single voice lane only. */
  voiceIndex?: number | null;
  /** Human-readable source staff label at sync time. */
  staffLabel: string;
  /** Source score title at sync time. */
  sourceTitle: string;
  /** Signature of source content used for stale/update checks. */
  sourceSignature: string;
  /** ISO timestamp when source was last known during sync. */
  sourceUpdatedAt: string;
  /** ISO timestamp when this part was last synced. */
  syncedAt: string;
}

export interface Composition {
  id?: string;
  title: string;
  tempo: number;
  timeSignature: string; // e.g., "4/4", "3/4"
  keySignature: string; // e.g., "C", "G", "F"
  staves: Staff[];
  /** When true, the first measure is an anacrusis (pickup / upbeat measure). */
  anacrusis?: boolean;
  /** How many beats the anacrusis measure contains (1 … beatsPerMeasure−1). Default 1. */
  pickupBeats?: number;
  /** When true, measure numbers are displayed above the first staff. Default true. */
  showMeasureNumbers?: boolean;
  /** When true, chord symbols are played during playback. Default false. */
  playChords?: boolean;
  /** Optional author/composer name */
  author?: string;
  /** Optional arranger name */
  arrangedBy?: string;
  /** Privacy/sharing level: 'private' (default), 'shared' (with specific emails), or 'public' */
  privacy?: PrivacyLevel;
  /** List of email addresses to share with (only used when privacy is 'shared') */
  sharedEmails?: string[];
  /**
   * What shared/public viewers are allowed to do.
   * 'view'  → read-only access (default)
   * 'edit'  → full editing access
   * Only applies when privacy is 'shared' or 'public'.
   */
  sharePermission?: 'view' | 'edit';
  /** Automatically set when composition is created */
  createdAt?: Date;
  /** Automatically updated when composition is modified */
  updatedAt?: Date;
  userId?: string;
  /** Owner profile info captured for ownership display and transfer UX. */
  ownerEmail?: string;
  ownerName?: string;
  /** Active ownership transfer request id, if any. */
  pendingOwnershipTransferId?: string;
  /** Optional pending transfer expiration timestamp. */
  pendingOwnershipTransferExpiresAt?: Date;
  /** UID of the last user who saved the composition (may differ from userId for public/shared edits) */
  modifiedBy?: string;
  /** Engraving mode used for score rendering and controls. */
  notationSystem?: NotationSystem;
  /** Horizontal spacing profile for Gregorian chant rendering. */
  chantSpacingDensity?: GregorianChantSpacingDensity;
  /** Performance profile for chant ornaments (interpretive timing). */
  chantInterpretation?: GregorianChantInterpretation;
  /** Present when this document is a linked derived part from a full score staff. */
  linkedPartSource?: LinkedPartSource;
}

export type Instrument = 
  | 'piano'
  | 'organ'
  | 'guitar'
  | 'violin'
  | 'strings'
  | 'choir'
  | 'brass'
  | 'synth'
  | 'flute';
